### ISSUE TITLE
请问live2d还有办法下载吗

### ISSUE THREAD

**Issue by Ir-Phen** [lovegaoshi/biliNFT#5]
收藏集详细信息原本的接口
https://api.bilibili.com/x/vas/dlc_act/act/item/list?act_id=(\d+)
现在只返回一个{}

**Comment by lovegaoshi** [comment]
https://github.com/lovegaoshi/biliNFT/commit/346c3acd220ec1ae3c2c18bb4906d26334d44f02#diff-80801d3541035dcb86ad7780985e0071dc56abf18701e9a06e983f4f0ecaf977
